version: '3.8'

services:
  dev-db:
    image: postgres:latest
    container_name: nestjs-dev-db
    environment:
      POSTGRES_USER: nest-user
      POSTGRES_PASSWORD: nest-password
      POSTGRES_DB: nest-pg-db
    ports:
      - '5434:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped

  test-db:
    image: postgres:latest
    container_name: nestjs-test-db
    environment:
      POSTGRES_USER: nest-user
      POSTGRES_PASSWORD: nest-password
      POSTGRES_DB: nest-pg-db
    ports:
      - '5435:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_dev_data:
  postgres_test_data:
